### ISSUE TITLE
Doubt on line no 16 for file io.h

### ISSUE THREAD

**Issue by devtrace404** [tomsmeding/editor#10]
Hello Tom,

```
inline bool operator==(const Colour &a,const Colour &b){
    return a.r==b.r&&a.g==b.g&&a.b==b.b;
}
```

I could not understand syntax for the above code. Can you please tell the usage of == operator in the above function.

**Comment by tomsmeding** [comment]
Here I overload the `==` operator for two `Colour` arguments, so I can later easily compare two of those for equality. `Colour` is a struct which I defined right above. I suggest you look up [operator overloading](http://www.tutorialspoint.com/cplusplus/cpp_overloading.htm).

**Comment by tomsmeding** [comment]
By the way, if I may ask a question; how did you find this project? It's not exactly on top of the searches.

**Comment by devtrace404** [comment]
Thank you for your reply Tom. 
Replying to your question about finding this project. I searched tex editor on github and then add language C++ filter. Your project was on first page. Thats how I got it.

**Comment by tomsmeding** [comment]
Thanks :) Still wondering, but that doesn't matter.
Closing this issue as I think it's resolved.
