### ISSUE TITLE
dd doesn't really work correctly

### ISSUE THREAD

**Issue by lieuwex** [tomsmeding/editor#20]
it skips a line further than should actually be the case

standing on:
```
function () {
kaas;|
kaas;
}
```

when I press dd I expect:
```
function () {
kaas;|
}
```

but I get:
```
function () {
kaas;
|}
```

**Comment by tomsmeding** [comment]
Maybe you should fix your own stuff before accusing me of introducing bugs ;)
https://github.com/tomsmeding/editor/commit/097f6dd0ecc000b94a9aa641203ed9f789161f57#diff-fc169ca4ea5dab54ba9b542a4f819de6R1074

Fix: s/repcount/repcount-1

**Comment by lieuwex** [comment]
If that fixes it, then this seems to be fixed in baa9477780a642b3d3a2d8b933866483ef6a2e7c but broken again in 76e751fa57314732079e84f5722ba75a18aedff1.

**Comment by lieuwex** [comment]
Oh my god I'm sorry, I was running an older version all the time, I didn't notice the output binary name was changed. Everything runs correctly.

**Comment by tomsmeding** [comment]
⛄️
