### ISSUE TITLE
Procedure to execute and contribute to editor project

### ISSUE THREAD

**Issue by devtrace404** [tomsmeding/editor#7]
Hello,
I am interested in contributing to editor project. As you mentioned that this is a text editor that work like Vim editor. Can you please tell me how to start this editor on terminal (using mac ). Also please mention some ways to contribute to this project.

**Comment by tomsmeding** [comment]
Hi there,
Thanks for your interest in this project! This is a side project of mine. Please be aware that this is not (yet?) production-quality software! I'll be away this afternoon, but I'll get back to you shortly.
Cheers,
Tom

**Comment by devtrace404** [comment]
Hello Tom,
Thank you for your reply. Can you give me your Email id so that I can contact you in future.

**Comment by tomsmeding** [comment]
Hi,
Thanks for reaching out. I'm home now, so I can answer your questions more thoroughly.

For running editor on mac, you need to have lua 5.3 installed. If you have [homebrew](http://brew.sh), you can install the right version with `brew install lua53` (you might need to run `brew tap homebrew/versions` first). Then you can compile editor with a simple call to `make`; the executable to run is `./main` then. Let me know if that works out.

This project is still very young and there are lots of things I still want to fix and change. Therefore, I'd like to keep this project to myself for the time being. But if you have any questions, feel free to ask (here, for example). (To prevent spam, I'm not going to post my e-mail address here. Sorry.)

Cheers,
Tom
