### ISSUE TITLE
Make command not executing (using mac)

### ISSUE THREAD

**Issue by devtrace404** [tomsmeding/editor#9]
Correct me if I am doing wrong here. I entered the editor folder and wrote "**make**" command and it shows following error. 
<img width="729" alt="screenshot 2016-02-15 14 47 07" src="https://cloud.githubusercontent.com/assets/7972666/13044292/652095cc-d3f3-11e5-9364-393f2d91d437.png">

I thought there is problem with Lua here but then I checked that Lua is installed on my machine and I get following output when I checked Lua version. 
<img width="546" alt="screenshot 2016-02-15 14 47 25" src="https://cloud.githubusercontent.com/assets/7972666/13044323/8d9416e6-d3f3-11e5-9a05-63880a28a222.png">
Can you please help
Pawan

**Comment by tomsmeding** [comment]
The makefile assumes that you have lua installed with the brew formula "lua53". Otherwise, everyone has it installed in a different location. Please run `brew tap homebrew/versions`; `brew install lua53`. Then it should work fine.

**Comment by devtrace404** [comment]
Thank your for your reply Tom. 
(Please bear with me as I am a newbie in programming) 
Now when I try to run make command it shows following output
<img width="732" alt="screenshot 2016-02-15 16 03 18" src="https://cloud.githubusercontent.com/assets/7972666/13046238/a9b76436-d3fd-11e5-9ee8-f1e4d65f8177.png">
I thought running this command will show me text editor screen on terminal like Vim (may be I am wrong). 
**Now my question here is how to see this text editor on terminal ??**

pawan

**Comment by tomsmeding** [comment]
Hi,

Congrats, you successfully built editor :)
You can run the program by typing `./main` in that folder. If you want to always be able to run the editor, you can `cp main /usr/local/bin/editor`. But you'd have to do that every time you re-build editor.

Tom

**Comment by devtrace404** [comment]
Thanks for your kind help Tom,
After ./main command now I am getting editor on my screen as 
<img width="736" alt="screenshot 2016-02-15 20 00 40" src="https://cloud.githubusercontent.com/assets/7972666/13051390/0abb5bae-d41f-11e5-86ba-2d76c0725b93.png">

Can you please tell me **how to save the text file in the editor after inserting the text**

Pawan

**Comment by tomsmeding** [comment]
Hi Pawan,

I suggest you look up some information on how Vim works. I just found [openvim.com](http://openvim.com/), maybe that works for you? Be aware though that support in editor is rather limited as of now. Documentation is also quite absent.
If you're just curious into a "hacker's editor", please look at Vim.

Tom

**Comment by devtrace404** [comment]
Hello Tom,
When the text editor screen appears on the terminal after ./main command. Now i am able to write text on the screen. I have 2 questions :- 
1. What really can I do with the text I am writing( saving text anywhere)
2. In this text editor are we just able to write text on the screen or can we do anything else with the text.

**Comment by tomsmeding** [comment]
In this editor you can write text, do a few common operations on the text, and save it to files and load it from files. There isn't really anything more yet.
- `:` — evaluate editor command (`:quit`, `:write`, `:wq`, `:qall`, `:tab[npN]`, `:edit`, and some more)
- `h` — go left
- `l` — go right
- `j` — go down
- `k` — go up
- `{` — go one paragraph back
- `}` — go one paragraph forward
- `w` — move to next beginning of a word
- `b` — move to previous beginning of a word
- `gg` — move to top of file
- `G` — move to end of file
- `0` — move all the way to the left
- `^` — move all the way to the left, but staying right of indentation
- `+` — go forwards a line
- `_` — go forwards `repcount-1` lines
- `-` — go backwards a line
- `%` — go to `repcount`% in the file (see below)
- `$` — end of line
- `i` — insert mode
- `a` — append insert mode
- `I` — insert mode after `^`
- `A` — append mode after `$`
- `o` — new line after and insert
- `O` — new line before and insert
- `f` — find the next character you type in the line
- `F` — `f`, but then backwards
- `t` — `f`, but then end right before that char
- `T` — `t`, but then backwards
- `C` — change till end of line
- `D` — delete till end of line

Often, when you type a number before a command, that command will be executed so many times. This number is called the `repcount`.

That's the commands the editor supports now. Look in any vim documentation for more information.

**Comment by lieuwex** [comment]
@tomsmeding: this handy list can go in the readme, if you ask me.

**Comment by tomsmeding** [comment]
Sure, but this is the exact kind of documentation that'll go out of date _very quickly_. So maybe with a warning?

**Comment by devtrace404** [comment]
Hello Tom,
Yes you can just add the functioning of each file in the project and simple data flow between the files to show how the project is working. I know its a lot of task but if you could add it, It would be very thankful of you

**Comment by tomsmeding** [comment]
Sorry, I told you before, I have other things to do besides this too. I'm in university and can't just go on doing random stuff that'll take me days of work.
